<?php

namespace Brzozowski\IntelliHomeBundle\Entity;

/**
 * TemporaryDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemporaryDataRepository extends \Doctrine\ORM\EntityRepository
{
}
