<?php

namespace Brzozowski\IntelliHomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WeatherStationRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class WeatherStationRepository extends EntityRepository
{
}
